[database]
type = "SQLite"

[notify]
chazuo_threshold = 10
kongtiao_threshold = 10
yue_threshold = 10

[student]
id = "22020007067"
electricity_fee = 0.54
account = "235150"

[cron]
interval = 5
crontab = "*/5 * * * *"

[visualize]
port = 8501
title = "Electricity!"
icon = "⚡"

[database.MySQL]
host = "localhost"
port = 3306
user = "your_username"
password = "your_password"
database_name = "your_database_name"

[database.SQLite]
file_path = "Electricity.db"

[student.equipments.chazuo]
equipmentInfoId = "10.150.132.76#00066"
roomName = "125"
