[database]
type = "SQLite" # 数据库类型，支持 SQLite 和 MySQL

[notify]
chazuo_threshold = 10   # 插座电量阈值，单位为度
kongtiao_threshold = 10 # 空调电量阈值，单位为度
yue_threshold = 10      # 校园卡余额阈值，单位为元

[notify.email]
smtp_server = "smtp.163.com"
smtp_port = 465
from_email = "##@163.com"
to_email = ["##@163.com", "##@qq.com", "##@qq.com", "##@qq.com", "##@qq.com"]
email_password = "###"

[student]
id = "your_student_id" # 学号，请务必填写
electricity_fee = 0.54 # 电费单价，单位为 RMB/度

[cron]
interval = 5            # 定时任务执行间隔，单位为分钟，例如 5 表示每 5 分钟执行一次
crontab = "*/5 * * * *" # 定时任务执行时间，例如 "*/5 * * * *" 表示每 5 分钟执行一次

[visualize]
port = 8501            # 服务端口
title = "Electricity!" # 网站标题
icon = "⚡"             # 网站图标

[database.MySQL] # MySQL 数据库配置
host = "localhost"
port = 3306
user = "your_username"
password = "your_password"
database_name = "your_database_name"

[database.SQLite] # SQLite 数据库配置，初始化后会替换成绝对路径
file_path = "Electricity.db"