[database]
type = "SQLite" # 数据库类型，支持 SQLite 和 MySQL

[notify]
chazuo_threshold = 10
kongtiao_threshold = 10

[student]
id = "your_student_id"
electricity_fee = 0.54

[database.MySQL]
host = "localhost"
port = 3306
user = "your_username"
password = "your_password"
database_name = "your_database_name"

[database.SQLite]
file_path = "Electricity.db"

[notify.bark]
# https://bark.day.app/
enabled = false
device_token = "your_device_token"
