[database]
type = "SQLite" # 数据库类型，支持 SQLite 和 MySQL

[notify]
chazuo_threshold = 10   # 插座电量阈值，单位为度
kongtiao_threshold = 10 # 空调电量阈值，单位为度

[student]
id = "your_student_id" # 学号，请务必填写
electricity_fee = 0.54 # 电费单价，单位为 RMB/度

[cron]
interval = 5            # 定时任务执行间隔，单位为分钟，例如 5 表示每 5 分钟执行一次
crontab = "*/5 * * * *" # 定时任务执行时间，例如 "*/5 * * * *" 表示每 5 分钟执行一次


[visualize]
title = "Electricity!" # 可视化标题

[database.MySQL] # MySQL 数据库配置
host = "localhost"
port = 3306
user = "your_username"
password = "your_password"
database_name = "your_database_name"

[database.SQLite] # SQLite 数据库配置，初始化后会替换成绝对路径
file_path = "Electricity.db"

[notify.bark] # Bark 配置，用于推送电量告警和充电提醒
# https://bark.day.app/
enabled = false
device_token = "your_device_token"
